spring:
  application:
    name: todo
  datasource:
    url: jdbc:h2:mem:tododb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

app:
  jwt-secret: thisismysupersecretkeythatislongenoughforhs256algorithm123456
  jwt-expiration: 86400000